// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: internal/proto/calculator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Пустое сообщение
type EmptyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{0}
}

// Запрос с указанием имени пользователя
type UsernameOnlyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Perms    bool   `protobuf:"varint,2,opt,name=perms,proto3" json:"perms,omitempty"`
}

func (x *UsernameOnlyRequest) Reset() {
	*x = UsernameOnlyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UsernameOnlyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsernameOnlyRequest) ProtoMessage() {}

func (x *UsernameOnlyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsernameOnlyRequest.ProtoReflect.Descriptor instead.
func (*UsernameOnlyRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *UsernameOnlyRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UsernameOnlyRequest) GetPerms() bool {
	if x != nil {
		return x.Perms
	}
	return false
}

// Сообщение о наличии ошибки
type ErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Сообщение о наличии ошибки с указанием номера агента
type AgentAndErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error []string `protobuf:"bytes,1,rep,name=error,proto3" json:"error,omitempty"`
	Agent int32    `protobuf:"varint,2,opt,name=agent,proto3" json:"agent,omitempty"`
}

func (x *AgentAndErrorResponse) Reset() {
	*x = AgentAndErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AgentAndErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAndErrorResponse) ProtoMessage() {}

func (x *AgentAndErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAndErrorResponse.ProtoReflect.Descriptor instead.
func (*AgentAndErrorResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *AgentAndErrorResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *AgentAndErrorResponse) GetAgent() int32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

// Запрос на подсчет выражения
type ExpSendRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username   string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id         string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Expression string `protobuf:"bytes,3,opt,name=expression,proto3" json:"expression,omitempty"`
}

func (x *ExpSendRequest) Reset() {
	*x = ExpSendRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpSendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpSendRequest) ProtoMessage() {}

func (x *ExpSendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpSendRequest.ProtoReflect.Descriptor instead.
func (*ExpSendRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *ExpSendRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExpSendRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExpSendRequest) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

// Запрос на результат выражения
type ExpCheckRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Id       string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ExpCheckRequest) Reset() {
	*x = ExpCheckRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpCheckRequest) ProtoMessage() {}

func (x *ExpCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpCheckRequest.ProtoReflect.Descriptor instead.
func (*ExpCheckRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{5}
}

func (x *ExpCheckRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ExpCheckRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ExpCheckResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expression     string `protobuf:"bytes,1,opt,name=expression,proto3" json:"expression,omitempty"`
	Finished       bool   `protobuf:"varint,2,opt,name=finished,proto3" json:"finished,omitempty"`
	DivByZeroError bool   `protobuf:"varint,3,opt,name=divByZeroError,proto3" json:"divByZeroError,omitempty"`
	Result         string `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	Agent          int32  `protobuf:"varint,5,opt,name=agent,proto3" json:"agent,omitempty"`
	Error          string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	Username       string `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *ExpCheckResponse) Reset() {
	*x = ExpCheckResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpCheckResponse) ProtoMessage() {}

func (x *ExpCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpCheckResponse.ProtoReflect.Descriptor instead.
func (*ExpCheckResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{6}
}

func (x *ExpCheckResponse) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *ExpCheckResponse) GetFinished() bool {
	if x != nil {
		return x.Finished
	}
	return false
}

func (x *ExpCheckResponse) GetDivByZeroError() bool {
	if x != nil {
		return x.DivByZeroError
	}
	return false
}

func (x *ExpCheckResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExpCheckResponse) GetAgent() int32 {
	if x != nil {
		return x.Agent
	}
	return 0
}

func (x *ExpCheckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ExpCheckResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Запрос на все выражения
type ExpsGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expressions []*ExpCheckResponse `protobuf:"bytes,1,rep,name=expressions,proto3" json:"expressions,omitempty"`
	Error       []string            `protobuf:"bytes,2,rep,name=error,proto3" json:"error,omitempty"`
}

func (x *ExpsGetResponse) Reset() {
	*x = ExpsGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpsGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpsGetResponse) ProtoMessage() {}

func (x *ExpsGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpsGetResponse.ProtoReflect.Descriptor instead.
func (*ExpsGetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{7}
}

func (x *ExpsGetResponse) GetExpressions() []*ExpCheckResponse {
	if x != nil {
		return x.Expressions
	}
	return nil
}

func (x *ExpsGetResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

// Ответ на получение времени операций + таймаутов
type TimesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Summation      int64    `protobuf:"varint,1,opt,name=summation,proto3" json:"summation,omitempty"`
	Substraction   int64    `protobuf:"varint,2,opt,name=substraction,proto3" json:"substraction,omitempty"`
	Multiplication int64    `protobuf:"varint,3,opt,name=multiplication,proto3" json:"multiplication,omitempty"`
	Division       int64    `protobuf:"varint,4,opt,name=division,proto3" json:"division,omitempty"`
	AgentTimeout   int64    `protobuf:"varint,5,opt,name=agentTimeout,proto3" json:"agentTimeout,omitempty"`
	Error          []string `protobuf:"bytes,6,rep,name=error,proto3" json:"error,omitempty"`
	Username       string   `protobuf:"bytes,7,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *TimesResponse) Reset() {
	*x = TimesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimesResponse) ProtoMessage() {}

func (x *TimesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimesResponse.ProtoReflect.Descriptor instead.
func (*TimesResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{8}
}

func (x *TimesResponse) GetSummation() int64 {
	if x != nil {
		return x.Summation
	}
	return 0
}

func (x *TimesResponse) GetSubstraction() int64 {
	if x != nil {
		return x.Substraction
	}
	return 0
}

func (x *TimesResponse) GetMultiplication() int64 {
	if x != nil {
		return x.Multiplication
	}
	return 0
}

func (x *TimesResponse) GetDivision() int64 {
	if x != nil {
		return x.Division
	}
	return 0
}

func (x *TimesResponse) GetAgentTimeout() int64 {
	if x != nil {
		return x.AgentTimeout
	}
	return 0
}

func (x *TimesResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *TimesResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Запрос на установку времени операций + таймаутов
type TimesSetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username       string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Summation      int64  `protobuf:"varint,2,opt,name=summation,proto3" json:"summation,omitempty"`
	Substraction   int64  `protobuf:"varint,3,opt,name=substraction,proto3" json:"substraction,omitempty"`
	Multiplication int64  `protobuf:"varint,4,opt,name=multiplication,proto3" json:"multiplication,omitempty"`
	Division       int64  `protobuf:"varint,5,opt,name=division,proto3" json:"division,omitempty"`
	AgentTimeout   int64  `protobuf:"varint,6,opt,name=agentTimeout,proto3" json:"agentTimeout,omitempty"`
}

func (x *TimesSetRequest) Reset() {
	*x = TimesSetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimesSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimesSetRequest) ProtoMessage() {}

func (x *TimesSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimesSetRequest.ProtoReflect.Descriptor instead.
func (*TimesSetRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{9}
}

func (x *TimesSetRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *TimesSetRequest) GetSummation() int64 {
	if x != nil {
		return x.Summation
	}
	return 0
}

func (x *TimesSetRequest) GetSubstraction() int64 {
	if x != nil {
		return x.Substraction
	}
	return 0
}

func (x *TimesSetRequest) GetMultiplication() int64 {
	if x != nil {
		return x.Multiplication
	}
	return 0
}

func (x *TimesSetRequest) GetDivision() int64 {
	if x != nil {
		return x.Division
	}
	return 0
}

func (x *TimesSetRequest) GetAgentTimeout() int64 {
	if x != nil {
		return x.AgentTimeout
	}
	return 0
}

type TimesSetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Times *TimesResponse `protobuf:"bytes,1,opt,name=times,proto3" json:"times,omitempty"`
	Error []string       `protobuf:"bytes,2,rep,name=error,proto3" json:"error,omitempty"`
}

func (x *TimesSetResponse) Reset() {
	*x = TimesSetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TimesSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimesSetResponse) ProtoMessage() {}

func (x *TimesSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimesSetResponse.ProtoReflect.Descriptor instead.
func (*TimesSetResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{10}
}

func (x *TimesSetResponse) GetTimes() *TimesResponse {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *TimesSetResponse) GetError() []string {
	if x != nil {
		return x.Error
	}
	return nil
}

// Ответ
type MonitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	States []*MonitorResponse_SingleObj `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
}

func (x *MonitorResponse) Reset() {
	*x = MonitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse) ProtoMessage() {}

func (x *MonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse.ProtoReflect.Descriptor instead.
func (*MonitorResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{11}
}

func (x *MonitorResponse) GetStates() []*MonitorResponse_SingleObj {
	if x != nil {
		return x.States
	}
	return nil
}

// Пинги
type HeartbeatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID int32 `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetAgentID() int32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type ResultRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID        int32  `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	DivByZeroError bool   `protobuf:"varint,2,opt,name=divByZeroError,proto3" json:"divByZeroError,omitempty"`
	Result         string `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{13}
}

func (x *ResultRequest) GetAgentID() int32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

func (x *ResultRequest) GetDivByZeroError() bool {
	if x != nil {
		return x.DivByZeroError
	}
	return false
}

func (x *ResultRequest) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

type ExpUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID int32  `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	Parts   string `protobuf:"bytes,2,opt,name=parts,proto3" json:"parts,omitempty"`
}

func (x *ExpUpdateRequest) Reset() {
	*x = ExpUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpUpdateRequest) ProtoMessage() {}

func (x *ExpUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpUpdateRequest.ProtoReflect.Descriptor instead.
func (*ExpUpdateRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{14}
}

func (x *ExpUpdateRequest) GetAgentID() int32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

func (x *ExpUpdateRequest) GetParts() string {
	if x != nil {
		return x.Parts
	}
	return ""
}

type ExpSeekRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID int32 `protobuf:"varint,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
}

func (x *ExpSeekRequest) Reset() {
	*x = ExpSeekRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpSeekRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpSeekRequest) ProtoMessage() {}

func (x *ExpSeekRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpSeekRequest.ProtoReflect.Descriptor instead.
func (*ExpSeekRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{15}
}

func (x *ExpSeekRequest) GetAgentID() int32 {
	if x != nil {
		return x.AgentID
	}
	return 0
}

type ExpSeekResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Found        bool           `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	Expression   string         `protobuf:"bytes,2,opt,name=expression,proto3" json:"expression,omitempty"`
	Times        *TimesResponse `protobuf:"bytes,3,opt,name=times,proto3" json:"times,omitempty"`
	ExpressionID string         `protobuf:"bytes,4,opt,name=expressionID,proto3" json:"expressionID,omitempty"`
}

func (x *ExpSeekResponse) Reset() {
	*x = ExpSeekResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpSeekResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpSeekResponse) ProtoMessage() {}

func (x *ExpSeekResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpSeekResponse.ProtoReflect.Descriptor instead.
func (*ExpSeekResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{16}
}

func (x *ExpSeekResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *ExpSeekResponse) GetExpression() string {
	if x != nil {
		return x.Expression
	}
	return ""
}

func (x *ExpSeekResponse) GetTimes() *TimesResponse {
	if x != nil {
		return x.Times
	}
	return nil
}

func (x *ExpSeekResponse) GetExpressionID() string {
	if x != nil {
		return x.ExpressionID
	}
	return ""
}

type ExpConfirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AgentID      string `protobuf:"bytes,1,opt,name=agentID,proto3" json:"agentID,omitempty"`
	ExpressionID string `protobuf:"bytes,2,opt,name=expressionID,proto3" json:"expressionID,omitempty"`
}

func (x *ExpConfirmRequest) Reset() {
	*x = ExpConfirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpConfirmRequest) ProtoMessage() {}

func (x *ExpConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpConfirmRequest.ProtoReflect.Descriptor instead.
func (*ExpConfirmRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{17}
}

func (x *ExpConfirmRequest) GetAgentID() string {
	if x != nil {
		return x.AgentID
	}
	return ""
}

func (x *ExpConfirmRequest) GetExpressionID() string {
	if x != nil {
		return x.ExpressionID
	}
	return ""
}

type MonitorResponse_SingleObj struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	State int32 `protobuf:"varint,2,opt,name=state,proto3" json:"state,omitempty"`
}

func (x *MonitorResponse_SingleObj) Reset() {
	*x = MonitorResponse_SingleObj{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_proto_calculator_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MonitorResponse_SingleObj) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonitorResponse_SingleObj) ProtoMessage() {}

func (x *MonitorResponse_SingleObj) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_calculator_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonitorResponse_SingleObj.ProtoReflect.Descriptor instead.
func (*MonitorResponse_SingleObj) Descriptor() ([]byte, []int) {
	return file_internal_proto_calculator_proto_rawDescGZIP(), []int{11, 0}
}

func (x *MonitorResponse_SingleObj) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MonitorResponse_SingleObj) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

var File_internal_proto_calculator_proto protoreflect.FileDescriptor

var file_internal_proto_calculator_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x61, 0x6c, 0x63, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x22, 0x47, 0x0a, 0x13, 0x55, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x4f, 0x6e, 0x6c, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x65,
	0x72, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x70, 0x65, 0x72, 0x6d, 0x73,
	0x22, 0x25, 0x0a, 0x0d, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x43, 0x0a, 0x15, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x41, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x22, 0x5c, 0x0a, 0x0e,
	0x45, 0x78, 0x70, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x3d, 0x0a, 0x0f, 0x45, 0x78,
	0x70, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0xd6, 0x01, 0x0a, 0x10, 0x45, 0x78,
	0x70, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e,
	0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a,
	0x0a, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x08, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x69,
	0x76, 0x42, 0x79, 0x5a, 0x65, 0x72, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x64, 0x69, 0x76, 0x42, 0x79, 0x5a, 0x65, 0x72, 0x6f, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0x61, 0x0a, 0x0f, 0x45, 0x78, 0x70, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x45, 0x78, 0x70, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x52, 0x0b, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xeb, 0x01, 0x0a, 0x0d, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x6d, 0x6d, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x75, 0x6d, 0x6d,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x75, 0x62,
	0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x75, 0x6c,
	0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x08, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a,
	0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0xd7, 0x01, 0x0a, 0x0f, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x53, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x75, 0x6d, 0x6d, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x64, 0x69, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x6f, 0x75, 0x74, 0x22, 0x53, 0x0a,
	0x10, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x53, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x13, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x22, 0x7d, 0x0a, 0x0f, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x37, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x4d, 0x6f, 0x6e,
	0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x69, 0x6e,
	0x67, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x65, 0x73, 0x1a, 0x31,
	0x0a, 0x09, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x4f, 0x62, 0x6a, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74,
	0x65, 0x22, 0x2c, 0x0a, 0x10, 0x48, 0x65, 0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22,
	0x69, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x26, 0x0a, 0x0e, 0x64, 0x69,
	0x76, 0x42, 0x79, 0x5a, 0x65, 0x72, 0x6f, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0e, 0x64, 0x69, 0x76, 0x42, 0x79, 0x5a, 0x65, 0x72, 0x6f, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x42, 0x0a, 0x10, 0x45, 0x78,
	0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x61, 0x72, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x61, 0x72, 0x74, 0x73, 0x22, 0x2a,
	0x0a, 0x0e, 0x45, 0x78, 0x70, 0x53, 0x65, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x22, 0x96, 0x01, 0x0a, 0x0f, 0x45,
	0x78, 0x70, 0x53, 0x65, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x66, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66,
	0x6f, 0x75, 0x6e, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x12,
	0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f,
	0x6e, 0x49, 0x44, 0x22, 0x51, 0x0a, 0x11, 0x45, 0x78, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72,
	0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e,
	0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x49, 0x44, 0x12, 0x22, 0x0a, 0x0c, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x49, 0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x69, 0x6f, 0x6e, 0x49, 0x44, 0x32, 0xe8, 0x04, 0x0a, 0x13, 0x4f, 0x72, 0x63, 0x68, 0x65,
	0x73, 0x74, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x33,
	0x0a, 0x08, 0x4b, 0x69, 0x6c, 0x6c, 0x4f, 0x72, 0x63, 0x68, 0x12, 0x12, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x13,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x09, 0x4b, 0x69, 0x6c, 0x6c, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x41, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0b, 0x52, 0x65, 0x76, 0x69, 0x76, 0x65, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x12, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x41, 0x67, 0x65, 0x6e,
	0x74, 0x41, 0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3c, 0x0a, 0x07, 0x53, 0x65, 0x6e, 0x64, 0x45, 0x78, 0x70, 0x12, 0x14, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x41,
	0x6e, 0x64, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x34, 0x0a, 0x07, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x15,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x0d, 0x53, 0x65, 0x6e, 0x64, 0x48, 0x65, 0x61,
	0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x48, 0x65,
	0x61, 0x72, 0x74, 0x62, 0x65, 0x61, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13,
	0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x35, 0x0a, 0x0a, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x13, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x6d,
	0x70, 0x74, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x3a, 0x0a, 0x0c, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x16, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x45, 0x78, 0x70, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x53, 0x65, 0x65, 0x6b, 0x46, 0x6f,
	0x72, 0x45, 0x78, 0x70, 0x12, 0x14, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x53,
	0x65, 0x65, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x61, 0x6c,
	0x63, 0x2e, 0x45, 0x78, 0x70, 0x53, 0x65, 0x65, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x3e, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x54, 0x61, 0x6b, 0x65,
	0x45, 0x78, 0x70, 0x12, 0x17, 0x2e, 0x63, 0x61, 0x6c, 0x63, 0x2e, 0x45, 0x78, 0x70, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x63,
	0x61, 0x6c, 0x63, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x12, 0x5a, 0x10, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2f,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_proto_calculator_proto_rawDescOnce sync.Once
	file_internal_proto_calculator_proto_rawDescData = file_internal_proto_calculator_proto_rawDesc
)

func file_internal_proto_calculator_proto_rawDescGZIP() []byte {
	file_internal_proto_calculator_proto_rawDescOnce.Do(func() {
		file_internal_proto_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_proto_calculator_proto_rawDescData)
	})
	return file_internal_proto_calculator_proto_rawDescData
}

var file_internal_proto_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_proto_calculator_proto_goTypes = []interface{}{
	(*EmptyMessage)(nil),              // 0: calc.EmptyMessage
	(*UsernameOnlyRequest)(nil),       // 1: calc.UsernameOnlyRequest
	(*ErrorResponse)(nil),             // 2: calc.ErrorResponse
	(*AgentAndErrorResponse)(nil),     // 3: calc.AgentAndErrorResponse
	(*ExpSendRequest)(nil),            // 4: calc.ExpSendRequest
	(*ExpCheckRequest)(nil),           // 5: calc.ExpCheckRequest
	(*ExpCheckResponse)(nil),          // 6: calc.ExpCheckResponse
	(*ExpsGetResponse)(nil),           // 7: calc.ExpsGetResponse
	(*TimesResponse)(nil),             // 8: calc.TimesResponse
	(*TimesSetRequest)(nil),           // 9: calc.TimesSetRequest
	(*TimesSetResponse)(nil),          // 10: calc.TimesSetResponse
	(*MonitorResponse)(nil),           // 11: calc.MonitorResponse
	(*HeartbeatRequest)(nil),          // 12: calc.HeartbeatRequest
	(*ResultRequest)(nil),             // 13: calc.ResultRequest
	(*ExpUpdateRequest)(nil),          // 14: calc.ExpUpdateRequest
	(*ExpSeekRequest)(nil),            // 15: calc.ExpSeekRequest
	(*ExpSeekResponse)(nil),           // 16: calc.ExpSeekResponse
	(*ExpConfirmRequest)(nil),         // 17: calc.ExpConfirmRequest
	(*MonitorResponse_SingleObj)(nil), // 18: calc.MonitorResponse.SingleObj
}
var file_internal_proto_calculator_proto_depIdxs = []int32{
	6,  // 0: calc.ExpsGetResponse.expressions:type_name -> calc.ExpCheckResponse
	8,  // 1: calc.TimesSetResponse.times:type_name -> calc.TimesResponse
	18, // 2: calc.MonitorResponse.states:type_name -> calc.MonitorResponse.SingleObj
	8,  // 3: calc.ExpSeekResponse.times:type_name -> calc.TimesResponse
	0,  // 4: calc.OrchestratorService.KillOrch:input_type -> calc.EmptyMessage
	0,  // 5: calc.OrchestratorService.KillAgent:input_type -> calc.EmptyMessage
	0,  // 6: calc.OrchestratorService.ReviveAgent:input_type -> calc.EmptyMessage
	4,  // 7: calc.OrchestratorService.SendExp:input_type -> calc.ExpSendRequest
	0,  // 8: calc.OrchestratorService.Monitor:input_type -> calc.EmptyMessage
	12, // 9: calc.OrchestratorService.SendHeartbeat:input_type -> calc.HeartbeatRequest
	13, // 10: calc.OrchestratorService.SendResult:input_type -> calc.ResultRequest
	14, // 11: calc.OrchestratorService.UpdateResult:input_type -> calc.ExpUpdateRequest
	15, // 12: calc.OrchestratorService.SeekForExp:input_type -> calc.ExpSeekRequest
	17, // 13: calc.OrchestratorService.ConfirmTakeExp:input_type -> calc.ExpConfirmRequest
	2,  // 14: calc.OrchestratorService.KillOrch:output_type -> calc.ErrorResponse
	3,  // 15: calc.OrchestratorService.KillAgent:output_type -> calc.AgentAndErrorResponse
	3,  // 16: calc.OrchestratorService.ReviveAgent:output_type -> calc.AgentAndErrorResponse
	3,  // 17: calc.OrchestratorService.SendExp:output_type -> calc.AgentAndErrorResponse
	11, // 18: calc.OrchestratorService.Monitor:output_type -> calc.MonitorResponse
	2,  // 19: calc.OrchestratorService.SendHeartbeat:output_type -> calc.ErrorResponse
	0,  // 20: calc.OrchestratorService.SendResult:output_type -> calc.EmptyMessage
	0,  // 21: calc.OrchestratorService.UpdateResult:output_type -> calc.EmptyMessage
	16, // 22: calc.OrchestratorService.SeekForExp:output_type -> calc.ExpSeekResponse
	2,  // 23: calc.OrchestratorService.ConfirmTakeExp:output_type -> calc.ErrorResponse
	14, // [14:24] is the sub-list for method output_type
	4,  // [4:14] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_internal_proto_calculator_proto_init() }
func file_internal_proto_calculator_proto_init() {
	if File_internal_proto_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_proto_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EmptyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UsernameOnlyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AgentAndErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpSendRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpCheckRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpCheckResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpsGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimesSetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TimesSetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeartbeatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResultRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpSeekRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpSeekResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpConfirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_proto_calculator_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MonitorResponse_SingleObj); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_proto_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_calculator_proto_goTypes,
		DependencyIndexes: file_internal_proto_calculator_proto_depIdxs,
		MessageInfos:      file_internal_proto_calculator_proto_msgTypes,
	}.Build()
	File_internal_proto_calculator_proto = out.File
	file_internal_proto_calculator_proto_rawDesc = nil
	file_internal_proto_calculator_proto_goTypes = nil
	file_internal_proto_calculator_proto_depIdxs = nil
}
